/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import model.*;
/**
 *
 * @author Danieles
 */
public class FarmaciaForm extends javax.swing.JFrame {

    /**
     * Creates new form FarmaciaForm
     */
    DrugStore farmacia;
    
    public void assignDrugStore (DrugStore farmacia) {
        this.farmacia = farmacia;
    }
    public FarmaciaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shoppingCartList = new java.awt.List();
        productList = new java.awt.List();
        Catálogo = new java.awt.Label();
        details = new java.awt.Label();
        productDetails = new java.awt.List();
        addToCart = new java.awt.Button();
        carritoLabel = new java.awt.Label();
        payButton = new java.awt.Button();
        removeProduct = new java.awt.Button();
        receta = new java.awt.Button();
        recetaE = new java.awt.TextField();
        filtro = new java.awt.Label();
        filtrar = new javax.swing.JComboBox<>();
        precioTotal = new java.awt.TextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(20, 40, 80));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setOpacity(1);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(shoppingCartList, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 212, 201, 170));

        productList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productListActionPerformed(evt);
            }
        });
        getContentPane().add(productList, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 170, 330));

        Catálogo.setText("Catálogo");
        getContentPane().add(Catálogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 60, 30));

        details.setText("Detalles");
        getContentPane().add(details, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 19, -1, -1));
        getContentPane().add(productDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 49, 201, 110));

        addToCart.setLabel("Añadir al carrito");
        addToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartActionPerformed(evt);
            }
        });
        getContentPane().add(addToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        carritoLabel.setText("Carrito");
        getContentPane().add(carritoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        payButton.setLabel("Realizar Compra");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });
        getContentPane().add(payButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));

        removeProduct.setLabel("Quitar del carrito");
        removeProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeProductActionPerformed(evt);
            }
        });
        getContentPane().add(removeProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        receta.setLabel("Receta Electronica");
        receta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recetaActionPerformed(evt);
            }
        });
        getContentPane().add(receta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));
        getContentPane().add(recetaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 120, 30));

        filtro.setText("Filtrar por:");
        getContentPane().add(filtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        filtrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Cremas", "Higiene Bucal", "Bebes", "Pastillas", "Suplementos" }));
        filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarActionPerformed(evt);
            }
        });
        getContentPane().add(filtrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 100, 30));

        precioTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioTotalActionPerformed(evt);
            }
        });
        getContentPane().add(precioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 60, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/FondoFarmacia.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productListActionPerformed
        // TODO add your handling code here:
        Product selected;
        int active;
        int active2;
        active2 = filtrar.getSelectedIndex();
        active = productList.getSelectedIndex();
        selected = farmacia.catalogo.categories.get(active2).prod.get(active);
        showProductDetails(selected);
    }//GEN-LAST:event_productListActionPerformed

    private void addToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartActionPerformed
        // TODO add your handling code here:
        int active;
        int active2;
        active = productList.getSelectedIndex();
        active2 = filtrar.getSelectedIndex();
        Product selected;
        selected = farmacia.catalogo.categories.get(active2).prod.get(active);
        farmacia.carro.addProduct(selected);
        float prec = 0;
        for (int i = 0; i < farmacia.carro.prods.size(); i++) {
            prec += farmacia.carro.prods.get(i).getPrice();
            String precStr = Float.toString(prec);
            precioTotal.setText(precStr);
        }
        showShoppingCart();
    }//GEN-LAST:event_addToCartActionPerformed

    private void removeProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeProductActionPerformed
        // TODO add your handling code here:
        int active;
        active = shoppingCartList.getSelectedIndex();
        Product selected;
        selected = farmacia.carro.prods.get(active);
        farmacia.carro.deleteProduct(selected);
        showShoppingCart();
        String prec = precioTotal.getText();
        float precioFl = Float.parseFloat(prec);
        String precStr = "";
        for (int i = 0; i < farmacia.carro.prods.size(); i++) {
            precioFl -= farmacia.carro.prods.get(i).getPrice();
            precStr = Float.toString(precioFl);
            precioTotal.setText(precStr);
        }
        showShoppingCart();
    }//GEN-LAST:event_removeProductActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        // TODO add your handling code here:
        PagoForm pago = new PagoForm();
        if ("".equals(precioTotal.getText())) {
            pago.setVisible(false);
        }else {
            pago.setVisible(true);
        }
    }//GEN-LAST:event_payButtonActionPerformed

    private void recetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recetaActionPerformed
        // TODO add your handling code here:
        int active;
        int active2;
        active = productList.getSelectedIndex();
        active2 = filtrar.getSelectedIndex();
        Product selected;
        selected = farmacia.catalogo.categories.get(active2).prod.get(active);
        farmacia.carro.addProduct(selected);
        float precioNormal = selected.getPrice();
        float dis = 0.3f;
        float descuento = precioNormal * dis;
        float precioDescontado = precioNormal - descuento;
        selected.setPrice(precioDescontado);
        String precioDescontadoStr = Float.toString(precioDescontado);
        
        if (!"".equals(recetaE.getText())) {
        farmacia.carro.addProduct(selected);
        shoppingCartList.add(selected.getName());
        //String precioStr = Float.toString(showPrice(selected));
        farmacia.carro.addProduct(selected);
        precioTotal.setText(precioDescontadoStr);
        }
    }//GEN-LAST:event_recetaActionPerformed

    private void filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarActionPerformed
        // TODO add your handling code here:
        showCategoryProducts();
    }//GEN-LAST:event_filtrarActionPerformed

    private void precioTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioTotalActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FarmaciaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FarmaciaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FarmaciaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FarmaciaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FarmaciaForm().setVisible(true);
            }
        });
    }
    
    public void showCategoryProducts () {
        productList.removeAll();
        if (filtrar.getSelectedIndex()== 0){
            for (int j = 0; j < farmacia.catalogo.getCategories().get(0).getProducts().size(); j++) {
                productList.add(farmacia.catalogo.getCategories().get(0).getProducts().get(j));
            }
        }
        if (filtrar.getSelectedIndex()== 1){
            for (int j = 0; j < farmacia.catalogo.getCategories().get(1).getProducts().size(); j++) {
                productList.add(farmacia.catalogo.getCategories().get(1).getProducts().get(j));
            }
        }
        if (filtrar.getSelectedIndex()== 2){
            for (int j = 0; j < farmacia.catalogo.getCategories().get(2).getProducts().size(); j++) {
                productList.add(farmacia.catalogo.getCategories().get(2).getProducts().get(j));
            }
        }
        if (filtrar.getSelectedIndex()== 3){
            for (int j = 0; j < farmacia.catalogo.getCategories().get(3).getProducts().size(); j++) {
                productList.add(farmacia.catalogo.getCategories().get(3).getProducts().get(j));
            }
        }
        if (filtrar.getSelectedIndex()== 4){
            for (int j = 0; j < farmacia.catalogo.getCategories().get(4).getProducts().size(); j++) {
                productList.add(farmacia.catalogo.getCategories().get(4).getProducts().get(j));
            }
        }
        if (filtrar.getSelectedIndex()== 5){
            for (int j = 0; j < farmacia.catalogo.getCategories().get(5).getProducts().size(); j++) {
                productList.add(farmacia.catalogo.getCategories().get(5).getProducts().get(j));
            }
        } 
    }
    
    public void showAll () {
        productList.removeAll();
        for (int i = 0; i < farmacia.catalogo.products.size(); i++) {
            productList.add(farmacia.catalogo.products.get(i).getName());
        }
    }
    
    public void showShoppingCart () {
        shoppingCartList.removeAll();
        for (int i = 0; i < farmacia.carro.prods.size(); i++) {
            shoppingCartList.add(farmacia.carro.prods.get(i).getName());
        }
    }
    public void showProductDetails (Product selected) {
        productDetails.removeAll();
        productDetails.add("Nombre: " + selected.getName());
        productDetails.add("Código: " + selected.getCode());
        productDetails.add("Prospecto: " + selected.getProspect());
        productDetails.add(selected.priceS() + " euros");
    }
    
    public float showPrice (Product selected) {
        float precio = selected.getPrice();
        return precio;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Catálogo;
    private java.awt.Button addToCart;
    private java.awt.Label carritoLabel;
    private java.awt.Label details;
    private javax.swing.JComboBox<String> filtrar;
    private java.awt.Label filtro;
    private javax.swing.JLabel fondo;
    private java.awt.Button payButton;
    private java.awt.TextField precioTotal;
    private java.awt.List productDetails;
    private java.awt.List productList;
    private java.awt.Button receta;
    private java.awt.TextField recetaE;
    private java.awt.Button removeProduct;
    private java.awt.List shoppingCartList;
    // End of variables declaration//GEN-END:variables
}
