/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.DrugStore;

/**
 *
 * @author danie
 */
public class IniciarSesionForm extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSeccionForm
     */
    public void assing(CuentasApp cuenta){
        this.cuenta = cuenta;
    }
    
    public void assignDrugStore (DrugStore farmacia, FarmaciaForm farmaciaform) {
        this.farmacia = farmacia;
        this.farmaciaform = farmaciaform;
    }
    
    public void assingForm(PagoForm pago){
        this.pago = pago;
    }
    
    public IniciarSesionForm() {
        initComponents();
        setBounds(500, 300, 300, 220);
        setVisible(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tNombre = new javax.swing.JTextField();
        tContraseña = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bAceptar = new java.awt.Button();
        bCancel = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        lNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(81, 120, 240));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(tNombre);
        tNombre.setBounds(110, 60, 140, 25);

        tContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tContraseñaKeyReleased(evt);
            }
        });
        getContentPane().add(tContraseña);
        tContraseña.setBounds(110, 90, 140, 25);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel2.setText("Iniciar Sesión");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 0, 210, 50);

        jPanel1.setBackground(new java.awt.Color(44, 193, 198));
        jPanel1.setLayout(null);

        bAceptar.setLabel("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(bAceptar);
        bAceptar.setBounds(161, 139, 70, 25);

        bCancel.setActionCommand("Cancelar");
        bCancel.setLabel("Cancelar");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });
        jPanel1.add(bCancel);
        bCancel.setBounds(49, 139, 70, 25);
        bCancel.getAccessibleContext().setAccessibleParent(this);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Password:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(39, 90, 90, 20);

        lNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lNombre.setText("User name:");
        jPanel1.add(lNombre);
        lNombre.setBounds(29, 61, 80, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 310, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_bCancelActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        comprobarCuenta();
    }//GEN-LAST:event_bAceptarActionPerformed

    private void tContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tContraseñaKeyReleased
        if (evt.getKeyChar() == '\n'){
            comprobarCuenta();
        }
    }//GEN-LAST:event_tContraseñaKeyReleased

    public void comprobarCuenta(){
        if (tNombre.getText().equals("Cire") && tContraseña.getText().equals("1234")) {                       
            farmaciaform.ponerNombre("Cirenia Monedero Espino");
            setVisible(false);
            try {
                if (pago.isVisible()){
                    pago.setVisible(false);
                    Pago2Form pago2 = new Pago2Form();                
                    pago2.assignDrugStore(farmacia, farmaciaform);
                    pago2.assingC(cuenta);
                    pago2.showPriceTotal();
                }
            } catch (Exception ex){}
                 
        } else if (tNombre.getText().equals("Dani") && tContraseña.getText().equals("4321")) {
            farmaciaform.ponerNombre("Daniel Martinez Muñoz");
            setVisible(false);
            try {
                if (pago.isVisible()){
                    pago.setVisible(false);
                    Pago3Form pago3 = new Pago3Form();                
                    pago3.assignDrugStore(farmacia, farmaciaform);
                    pago3.assingC(cuenta);
                    pago3.showPriceTotal(); 
                }
            }catch (Exception ex){}
            
        } else if (cuenta.verificarCuenta(tNombre.getText(), tContraseña.getText())){
            setVisible(false);
            Pago4Form pago4 = new Pago4Form();
            pago4.assignDrugStore(farmacia, farmaciaform);
            pago4.assing(cuenta);
            pago4.showPriceTotal(); 
        } else {
            JOptionPane.showMessageDialog(bAceptar, "Nombre o Contraseña incorrecta",
                            "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button bAceptar;
    private java.awt.Button bCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lNombre;
    private javax.swing.JPasswordField tContraseña;
    private javax.swing.JTextField tNombre;
    // End of variables declaration//GEN-END:variables
    public RegistrarseForm regis;
    public DrugStore farmacia;
    public PagoForm pago;
    public FarmaciaForm farmaciaform;
    public CuentasApp cuenta;
}
