/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import model.DrugStore;

/**
 *
 * @author danie
 */
public class PagoForm extends javax.swing.JFrame {

    /**
     * Creates new form PagoForm
     */
    DrugStore farmacia;
    
    public void assignDrugStore (DrugStore farmacia) {
        this.farmacia = farmacia;
    }
    public PagoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        street = new java.awt.TextField();
        labelStreet = new java.awt.Label();
        DireccionEntrega = new java.awt.Label();
        name = new java.awt.TextField();
        nombre = new java.awt.Label();
        postal = new java.awt.Label();
        postalCode = new java.awt.TextField();
        telefono = new java.awt.Label();
        telephone = new java.awt.TextField();
        tarjeta = new java.awt.Label();
        creditCard = new java.awt.TextField();
        realizarPago = new java.awt.Button();
        back = new java.awt.Button();
        periocidad = new java.awt.Label();
        puntual = new javax.swing.JRadioButton();
        semanal = new javax.swing.JRadioButton();
        mensual = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 350));
        setPreferredSize(new java.awt.Dimension(400, 350));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        street.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetActionPerformed(evt);
            }
        });
        getContentPane().add(street, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 100, 20));

        labelStreet.setText("Domicilio:");
        getContentPane().add(labelStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));

        DireccionEntrega.setText("Direccion Entrega");
        getContentPane().add(DireccionEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 20));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 100, 20));

        nombre.setText("Nombre:");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));

        postal.setText("Cod. Postal:");
        getContentPane().add(postal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        postalCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postalCodeActionPerformed(evt);
            }
        });
        getContentPane().add(postalCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 100, 20));

        telefono.setText("Telefono:");
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        telephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneActionPerformed(evt);
            }
        });
        getContentPane().add(telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 100, 20));

        tarjeta.setText("N. tarjeta:");
        getContentPane().add(tarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        creditCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditCardActionPerformed(evt);
            }
        });
        getContentPane().add(creditCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 100, -1));

        realizarPago.setLabel("Realizar pago");
        realizarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarPagoActionPerformed(evt);
            }
        });
        getContentPane().add(realizarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        back.setLabel("Atras");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 60, -1));

        periocidad.setText("Periodicidad");
        getContentPane().add(periocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        buttonGroup1.add(puntual);
        puntual.setText("Puntual");
        puntual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntualActionPerformed(evt);
            }
        });
        getContentPane().add(puntual, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        buttonGroup1.add(semanal);
        semanal.setText("Semanal");
        semanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semanalActionPerformed(evt);
            }
        });
        getContentPane().add(semanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        buttonGroup1.add(mensual);
        mensual.setText("Mensual");
        mensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mensualActionPerformed(evt);
            }
        });
        getContentPane().add(mensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void streetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetActionPerformed

    private void realizarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarPagoActionPerformed
        // TODO add your handling code here:
        if ("".equals(creditCard.getText())) {
            ErrorAlPagarForm error = new ErrorAlPagarForm();
            error.setVisible(true);
        }else {
        PagoRealizadoForm hecho = new PagoRealizadoForm();
        hecho.setVisible(true);
        }
    }//GEN-LAST:event_realizarPagoActionPerformed

    private void creditCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditCardActionPerformed

    private void telephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneActionPerformed

    private void postalCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postalCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postalCodeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void puntualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puntualActionPerformed

    private void semanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semanalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semanalActionPerformed

    private void mensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mensualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mensualActionPerformed
    
    public void showPrice () {
        float priceT = farmacia.carro.getTotalPrice();
        String priceStr = Float.toString(priceT);
        //totalPrice.add(priceStr);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label DireccionEntrega;
    private java.awt.Button back;
    private javax.swing.ButtonGroup buttonGroup1;
    private java.awt.TextField creditCard;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label labelStreet;
    private javax.swing.JRadioButton mensual;
    private java.awt.TextField name;
    private java.awt.Label nombre;
    private java.awt.Label periocidad;
    private java.awt.Label postal;
    private java.awt.TextField postalCode;
    private javax.swing.JRadioButton puntual;
    private java.awt.Button realizarPago;
    private javax.swing.JRadioButton semanal;
    private java.awt.TextField street;
    private java.awt.Label tarjeta;
    private java.awt.Label telefono;
    private java.awt.TextField telephone;
    // End of variables declaration//GEN-END:variables
}
