/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class RegistrarseForm extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarseForm
     */
    
    public void assing(CuentasApp cuentas){
        this.cuentas = cuentas;
    }
    
    public RegistrarseForm() {
        initComponents();
        setBounds(450, 200, 350, 350);
        setVisible(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        tApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tCorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tContraseña = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        tContraseña2 = new javax.swing.JPasswordField();
        button1 = new java.awt.Button();
        bAceptar = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 15, 47, 22);

        jLabel2.setText("Apellidos");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 15, 70, 22);
        getContentPane().add(tNombre);
        tNombre.setBounds(30, 40, 83, 25);

        tApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tApellidosActionPerformed(evt);
            }
        });
        getContentPane().add(tApellidos);
        tApellidos.setBounds(130, 40, 154, 25);

        jLabel3.setText("Nombre de usuario");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 70, 140, 20);

        tUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(tUserName);
        tUserName.setBounds(30, 90, 130, 25);

        jLabel4.setText("Correo electronico");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 120, 140, 20);

        tCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(tCorreo);
        tCorreo.setBounds(30, 140, 230, 25);

        jLabel5.setText("Contraseña");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 170, 110, 20);
        getContentPane().add(tContraseña);
        tContraseña.setBounds(30, 190, 120, 25);

        jLabel6.setText("Confirmar contraseña");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(170, 170, 140, 20);
        getContentPane().add(tContraseña2);
        tContraseña2.setBounds(170, 190, 120, 25);

        button1.setLabel("Cancelar");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(50, 250, 70, 25);

        bAceptar.setLabel("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(bAceptar);
        bAceptar.setBounds(170, 250, 70, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tApellidosActionPerformed

    private void tUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUserNameActionPerformed

    private void tCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCorreoActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_button1ActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        if (tNombre.getText().isEmpty() || tApellidos.getText().isEmpty() || 
                tUserName.getText().isEmpty() || tCorreo.getText().isEmpty() || 
                tContraseña.getText().isEmpty() || tContraseña2.getText().isEmpty()){
            JOptionPane.showMessageDialog(bAceptar, "Faltan datos por rellenar.",
                            "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(bAceptar, "Se ha registrado correctamente.",
                            "", JOptionPane.INFORMATION_MESSAGE);
            cuentas.añadirCuenta(tUserName.getText(), tContraseña.getText());
            cuentas.ponerDatos(tNombre.getText(), tApellidos.getText(), 
                    tUserName.getText(), tCorreo.getText(), tContraseña.getText());
            setVisible(false);
        }
    }//GEN-LAST:event_bAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarseForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button bAceptar;
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tApellidos;
    private javax.swing.JPasswordField tContraseña;
    private javax.swing.JPasswordField tContraseña2;
    private javax.swing.JTextField tCorreo;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tUserName;
    // End of variables declaration//GEN-END:variables
    public String name, apellidos, nameu, correo, contra;
    public CuentasApp cuentas;
    
}
